# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!([
  {email: "j3frea@gmail.com", password: "deliciousfish", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 31, current_sign_in_at: "2014-12-08 06:23:49", last_sign_in_at: "2014-12-02 11:06:09", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", church_id: 1},
])
Aka.create!([
  {song_id: 1, search_text: "in christ alone", display_text: "In Christ Alone"},
  {song_id: 2, search_text: "abide with me", display_text: "Abide With Me"},
  {song_id: 3, search_text: "speak o lord", display_text: "Speak, O Lord"},
  {song_id: 4, search_text: "how deep", display_text: "How Deep"},
  {song_id: 5, search_text: "endless praises", display_text: "Endless Praises"},
  {song_id: 6, search_text: "10000 reasons", display_text: "10,000 Reasons"},
  {song_id: 6, search_text: "bless the lord oh my soul", display_text: "Bless the Lord (10,000 Reasons)"},
  {song_id: 6, search_text: "ten thousand reasons", display_text: "10,000 Reasons"},
  {song_id: 7, search_text: "god immortal", display_text: "God Immortal"},
  {song_id: 8, search_text: "how deep the father’s love for us", display_text: "How Deep The Father’s Love For Us"},
  {song_id: 9, search_text: "cornerstone", display_text: "Cornerstone"},
  {song_id: 10, search_text: "let your kingdom come", display_text: "Let Your Kingdom Come"},
  {song_id: 11, search_text: "salvation belongs to our god", display_text: "Salvation Belongs to our God"},
  {song_id: 12, search_text: "jesus is lord", display_text: "Jesus is Lord"},
  {song_id: 13, search_text: "loved before the dawn of time", display_text: "Loved Before the Dawn of Time"},
  {song_id: 13, search_text: "salvations song", display_text: "Salvation's Song"},
  {song_id: 14, search_text: "as the deer", display_text: "As the Deer"},
  {song_id: 15, search_text: "o sacred king", display_text: "O Sacred King"},
  {song_id: 16, search_text: "love divine all loves excelling", display_text: "Love Divine, All Loves Excelling"},
  {song_id: 17, search_text: "amazing grace", display_text: "Amazing Grace"},
  {song_id: 18, search_text: "your blood speaks a better word", display_text: "Your Blood Speaks a Better Word"},
  {song_id: 18, search_text: "nothing but the blood", display_text: "Nothing but the Blood"},
  {song_id: 19, search_text: "here i am to worship", display_text: "Here I Am to Worship"},
  {song_id: 19, search_text: "light of the world", display_text: "Light of the World"},
  {song_id: 20, search_text: "we have seen your glory", display_text: "We have seen your glory"},
  {song_id: 21, search_text: "create in me a clean heart o god", display_text: "Create in me a clean heart, O God"},
  {song_id: 22, search_text: "blessing and honour", display_text: "Blessing and Honour"},
  {song_id: 23, search_text: "hark the herald angels sing", display_text: "Hark the Herald Angels Sing"},
  {song_id: 24, search_text: "o lord our lord how majestic", display_text: "O Lord, Our Lord (How Majestic is Your Name)"},
  {song_id: 24, search_text: "how majestic is your name", display_text: "How Majestic is Your Name (O Lord, Our Lord)"},
  {song_id: 25, search_text: "father into your courts i will enter", display_text: "Father Into Your Courts I Will Enter"},
  {song_id: 26, search_text: "standing in your presence", display_text: "Standing in Your Presence"},
  {song_id: 27, search_text: "beautiful lord wonderful saviour", display_text: "Beautiful Lord, Wonderful Saviour"},
  {song_id: 28, search_text: "your will not mine", display_text: "Your Will, Not Mine"},
  {song_id: 29, search_text: "tell out my soul", display_text: "Tell Out, My Soul"},
  {song_id: 30, search_text: "be still my soul", display_text: "Be Still My Soul"},
  {song_id: 31, search_text: "my soul finds rest in god alone", display_text: "My Soul Finds Rest in God Alone"},
  {song_id: 31, search_text: "psalm 62", display_text: "Psalm 62 (My Soul Finds Rest in God Alone)"},
  {song_id: 32, search_text: "sing to the king", display_text: "Sing To The King"},
  {song_id: 33, search_text: "how firm a foundation", display_text: "How Firm a Foundation"},
  {song_id: 34, search_text: "you alone can rescue", display_text: "You Alone Can Rescue"},
  {song_id: 34, search_text: "who o lord could save themselves", display_text: "Who, O Lord (You Alone Can Rescue)"},
  {song_id: 35, search_text: "before the throne of god above", display_text: "Before the Throne of God Above"},
  {song_id: 36, search_text: "come thou fount of every blessing", display_text: "Come Thou Fount of Every Blessing"},
  {song_id: 37, search_text: "jesus the name high over all", display_text: "Jesus The Name High Over All"},
  {song_id: 38, search_text: "show us christ", display_text: "Show Us Christ"},
  {song_id: 39, search_text: "for all youve done", display_text: "For All You've Done"},
  {song_id: 39, search_text: "my saviour redeemer", display_text: "My Saviour, Redeemer (For All You've Done)"},
  {song_id: 40, search_text: "a father to the fatherless", display_text: "A Father to the Fatherless"},
  {song_id: 41, search_text: "nothing in this world", display_text: "Nothing in this World"},
  {song_id: 42, search_text: "hungry i come to you", display_text: "Hungry, I Come to You"},
  {song_id: 43, search_text: "at the foot of the cross", display_text: "At The Foot of the Cross"},
  {song_id: 44, search_text: "here i am majesty", display_text: "Here I Am (Majesty)"},
  {song_id: 45, search_text: "merciful god", display_text: "Merciful God"},
  {song_id: 46, search_text: "there is a redeemer", display_text: "There is a Redeemer"},
  {song_id: 47, search_text: "you are the holy one", display_text: "You are the Holy One"},
  {song_id: 48, search_text: "jesus gods righteousness revealed", display_text: "Jesus, God's Righteousness Revealed"},
  {song_id: 49, search_text: "you laid aside your majesty", display_text: "You Laid Aside Your Majesty"},
  {song_id: 49, search_text: "i really want to worship you my lord", display_text: "I Really Want to Worship You My Lord"},
  {song_id: 50, search_text: "i will offer up my life", display_text: "I Will Offer Up My Life"},
  {song_id: 51, search_text: "no eye has seen", display_text: "No Eye Has Seen"},
  {song_id: 52, search_text: "lord i come to you", display_text: "Lord, I Come to You"},
  {song_id: 53, search_text: "father here i am", display_text: "Father Here I Am"},
  {song_id: 54, search_text: "change my heart o god", display_text: "Change My Heart, O God"},
  {song_id: 55, search_text: "guide me o thou great jehovah", display_text: "Guide Me, O Thou Great Jehovah"},
  {song_id: 56, search_text: "lord of the church", display_text: "Lord of the Church"},
  {song_id: 57, search_text: "lord reign in me", display_text: "Lord Reign in Me"},
  {song_id: 57, search_text: "over all the earth", display_text: "Over all the Earth (Lord Reign in Me)"},
  {song_id: 58, search_text: "a frame so beautifully formed", display_text: "A Frame So Beautifully... (All My Shame)"},
  {song_id: 58, search_text: "all my shame", display_text: "All My Shame"},
  {song_id: 59, search_text: "when i survery", display_text: "When I Survery"},
  {song_id: 60, search_text: "be thou my vision", display_text: "Be Thou My Vision"},
  {song_id: 61, search_text: "above all powers", display_text: "Above All Powers"},
  {song_id: 62, search_text: "jesus thank you", display_text: "Jesus, Thank You"},
  {song_id: 63, search_text: "with a prayer", display_text: "With a Prayer (You fed the Hungry)"},
  {song_id: 64, search_text: "lord you are the author of my life", display_text: "Lord, You are the Author of my Life"},
  {song_id: 65, search_text: "be still for the presence of the lord", display_text: "Be Still (for the presence of the Lord)"},
  {song_id: 66, search_text: "holy spirit living breath of god", display_text: "Holy Spirit, Living Breath of God"},
  {song_id: 67, search_text: "call the man", display_text: "Call the Man (Eagles' Wings)"},
  {song_id: 67, search_text: "eagles wings", display_text: "Eagles' Wings (Call the Man)"},
  {song_id: 68, search_text: "wonderful merciful savior", display_text: "Wonderful, Merciful Savior"},
  {song_id: 69, search_text: "come people of the risen king", display_text: "Come People of the Risen King"},
  {song_id: 70, search_text: "i cannot tell", display_text: "I Cannot Tell"},
  {song_id: 71, search_text: "rock of ages", display_text: "Rock of Ages"},
  {song_id: 72, search_text: "take my life and let it be", display_text: "Take My Life and Let it Be"},
  {song_id: 73, search_text: "the whole earth", display_text: "The Whole Earth"},
  {song_id: 74, search_text: "the precious blood", display_text: "The Precious Blood"},
  {song_id: 75, search_text: "healing to the nations", display_text: "Healing To The Nations"},
  {song_id: 76, search_text: "name of all majesty", display_text: "Name of All Majesty"},
  {song_id: 77, search_text: "there is a higher throne", display_text: "There is a Higher Throne"},
  {song_id: 78, search_text: "well walk the land", display_text: "We'll Walk the Land"},
  {song_id: 79, search_text: "bayete nkosi", display_text: "Bayete Nkosi (Jabulani Africa)"},
  {song_id: 79, search_text: "jabulani africa", display_text: "Jabulani Africa"},
  {song_id: 80, search_text: "hosanna", display_text: "Hosanna (Praise Is Rising)"},
  {song_id: 80, search_text: "praise is rising", display_text: "Praise is Rising (Hosanna)"},
  {song_id: 81, search_text: "by faith we see the hand of god", display_text: "By Faith (we see the hand of God)"},
  {song_id: 82, search_text: "o church arise", display_text: "O Church, Arise"},
  {song_id: 83, search_text: "i the lord of sea and sky", display_text: "I the Lord of sea and sky"},
  {song_id: 84, search_text: "it is the cry of my heart", display_text: "It is the Cry of My Heart"},
  {song_id: 85, search_text: "jesus what a beautiful name", display_text: "Jesus, What a Beautiful Name"},
  {song_id: 86, search_text: "thank you for saving me", display_text: "Thank You for Saving Me"},
  {song_id: 87, search_text: "father let me dedicate", display_text: "Father, Let Me Dedicate"},
  {song_id: 88, search_text: "thou whose almighty word", display_text: "Thou, Whose Almighty Word"},
  {song_id: 89, search_text: "god of grace i turn my face", display_text: "God of Grace (I turn my face)"},
  {song_id: 90, search_text: "all my days i will sing", display_text: "All My Days (I will sing this song...)"},
  {song_id: 91, search_text: "and can it be", display_text: "And Can it Be"},
  {song_id: 92, search_text: "i lift my hands to the coming king", display_text: "I Lift My Hands (To the coming King)"},
  {song_id: 93, search_text: "god forgave my sin", display_text: "God Forgave My Sin"},
  {song_id: 94, search_text: "set my spirit free", display_text: "Set My Spirit Free"},
  {song_id: 95, search_text: "oh to see the dawn", display_text: "Oh, to see the Dawn"},
  {song_id: 96, search_text: "draw me close to you", display_text: "Draw Me Close to You"},
  {song_id: 96, search_text: "youre all i want", display_text: "You're all I want (Draw me close to you)"},
  {song_id: 97, search_text: "king of kings", display_text: "King of Kings, Majesty"},
  {song_id: 97, search_text: "majesty", display_text: "Majesty (King of Kings)"},
  {song_id: 98, search_text: "jesus is king", display_text: "Jesus is King (and I will extol him)"},
  {song_id: 99, search_text: "come now is the time to worship", display_text: "Come, Now Is The Time To Worship"},
  {song_id: 100, search_text: "open the eyes of my heart lord i want to see you", display_text: "Open The Eyes Of My Heart Lord (I Want To See You)"},
  {song_id: 102, search_text: "youre the word of god the father", display_text: "You're the Word of God the Father (Across The Lands)"},
  {song_id: 102, search_text: "across the lands", display_text: "Across The Lands (You're The Author Of Creation)"},
  {song_id: 102, search_text: "youre the author of creation", display_text: "Across The Lands (You're The Author Of Creation)"},
  {song_id: 103, search_text: "there is no other name", display_text: "There is No Other Name"},
  {song_id: 104, search_text: "at your feet we fall", display_text: "At Your Feet We Fall (Mighty Risen Lord)"},
  {song_id: 105, search_text: "all hail king jesus", display_text: "All Hail King Jesus (All Hail King Emmanuel)"},
  {song_id: 106, search_text: "blessed be your name", display_text: "Blessed Be Your Name (In The Land That Is Plentiful)"},
  {song_id: 107, search_text: "o jesus i have promised", display_text: "O Jesus, I Have Promised"},
  {song_id: 108, search_text: "all heaven declares", display_text: "All Heaven Declares (The Glory Of The Risen Lord)"},
  {song_id: 108, search_text: "forever he will be", display_text: "Forever He Will Be (All Heaven Declares)"},
  {song_id: 108, search_text: "forever you will be", display_text: "Forever You Will Be (All Heaven Declares)"},
  {song_id: 109, search_text: "all i once held dear", display_text: "All I Once Held Dear (Knowing You)"},
  {song_id: 109, search_text: "knowing you jesus", display_text: "Knowing You (All I Once Held Dear)"},
  {song_id: 110, search_text: "we will glorify", display_text: "We Will Glorify (Jesus Is The Name...)"},
  {song_id: 110, search_text: "jesus is the name we honour", display_text: "Jesus Is The Name We Honour"},
  {song_id: 111, search_text: "amazing love", display_text: "Amazing Love (My Lord, What Love Is This)"},
  {song_id: 111, search_text: "My Lord, What Love Is This", display_text: "my lord what love is this"},
  {song_id: 112, search_text: "thy word is a lamp unto my feet", display_text: "Thy Word (is a lamp unto my feet)"},
  {song_id: 113, search_text: "my jesus my saviour", display_text: "My Jesus My Saviour"},
  {song_id: 113, search_text: "shout to the lord", display_text: "Shout To The Lord (My Jesus My Saviour)"},
  {song_id: 114, search_text: "consider christ", display_text: "Consider Christ"},
  {song_id: 115, search_text: "jesus lover of my soul", display_text: "Jesus, Lover Of My Soul (I will never let you go)"},
  {song_id: 116, search_text: "crown him with many crowns", display_text: "Crown Him With Many Crowns"},
  {song_id: 117, search_text: "purify my heart", display_text: "Purify My Heart (Refiner's Fire)"},
  {song_id: 117, search_text: "refiners fire", display_text: "Refiner's Fire (Purify My Heart)"},
  {song_id: 118, search_text: "battle hymn", display_text: "Battle Hymn (There's A Sound On The Wind)"},
  {song_id: 118, search_text: "come on heavens children", display_text: "Come on Heaven's Children (There's A Sound On The Wind)"},
  {song_id: 118, search_text: "theres a sound on the wind like a victory song", display_text: "There's A Sound On The Wind (Like A Victory Song)"},
  {song_id: 119, search_text: "worthy is the lamb", display_text: "Worthy Is The Lamb (Thank You For The Cross, Lord)"},
  {song_id: 119, search_text: "thank you for the cross lord", display_text: "Thank You For The Cross, Lord (Worthy Is The Lamb)"},
  {song_id: 120, search_text: "there is a hope", display_text: "There is a Hope (that burns within my heart)"},
  {song_id: 121, search_text: "the splendor of the king", display_text: "The Splendour Of The King (How Great Is Our God)"},
  {song_id: 121, search_text: "how great is our god", display_text: "How Great Is Our God (The Splendour Of The King)"},
  {song_id: 122, search_text: "here i am once again", display_text: "Here I am once again (Pour Out My Heart)"},
  {song_id: 122, search_text: "pour out my heart", display_text: "Pour Out My Heart"},
  {song_id: 123, search_text: "i will sing your praises", display_text: "I Will Sing Your Praises (Father God I Wonder)"},
  {song_id: 123, search_text: "father god i wonder", display_text: "Father God I Wonder (I Will Sing Your Praises)"},
  {song_id: 124, search_text: "great in power", display_text: "Great in Power"},
  {song_id: 124, search_text: "praise him you heavens", display_text: "Praise Him You Heavens (Great in Power)"},
  {song_id: 125, search_text: "lord jesus here i stand before you", display_text: "Lord Jesus, Here I Stand Before You"},
  {song_id: 126, search_text: "i see the king of glory hosanna", display_text: "I See The King Of Glory (Hosanna)"},
  {song_id: 126, search_text: "hosanna", display_text: "Hosanna (I See The King Of Glory)"},
  {song_id: 127, search_text: "hide me now", display_text: "Hide Me Now (Still)"},
  {song_id: 127, search_text: "still", display_text: "Still (Hide Me Now)"},
  {song_id: 128, search_text: "i surrender", display_text: "I Surrender"},
  {song_id: 128, search_text: "to your majesty and your beauty", display_text: "To Your Majesty and Your Beauty (I Surrender)"},
  {song_id: 129, search_text: "i know not why gods wondrous grace", display_text: "I Know Not Why God's Wondrous Grace"},
  {song_id: 129, search_text: "i know whom i have believed", display_text: "I Know Whom I Have Believed"},
  {song_id: 130, search_text: "majesty and praise", display_text: "Majesty and Praise (No Other God)"},
  {song_id: 130, search_text: "no other god", display_text: "No Other God"},
  {song_id: 131, search_text: "faithful one so unchanging", display_text: "Faithful One (So Unchanging)"},
  {song_id: 132, search_text: "may the grace of christ my saviour", display_text: "May The Mind Of Christ My Saviour"},
  {song_id: 133, search_text: "look to the skies", display_text: "Look to the Skies"},
  {song_id: 134, search_text: "behold the lamb", display_text: "Behold the Lamb"},
  {song_id: 135, search_text: "alleluia praise ye the lord", display_text: "Alleluia Praise Ye The Lord"},
  {song_id: 136, search_text: "hope was born this night", display_text: "Hope Was Born This Night"},
  {song_id: 137, search_text: "these are the days of elijah", display_text: "These are the Days of Elijah"},
  {song_id: 137, search_text: "days of elijah", display_text: "Days of Elijah"},
  {song_id: 138, search_text: "what can i do", display_text: "What Can I Do"},
  {song_id: 138, search_text: "when i see the beauty", display_text: "When I See the Beauty"},
  {song_id: 139, search_text: "let the words of my mouth", display_text: "Let The Words Of My Mouth (All For You)"},
  {song_id: 139, search_text: "all for you", display_text: "All For You"},
  {song_id: 140, search_text: "meekness and majesty", display_text: "Meekness And Majesty"},
  {song_id: 141, search_text: "we three kings", display_text: "We Three Kings"},
  {song_id: 142, search_text: "when the music fades", display_text: "When the Music Fades"},
  {song_id: 142, search_text: "the heart of worship", display_text: "The Heart of Worship"}
])
Church.create!([
  {church_name: "Christ Church Hilton"},
])
Leader.create!([
  {leader_name: "James Cuénod", church_id: 1},
  {leader_name: "Caro Armstrong", church_id: 1},
  {leader_name: "Ali Gordijn", church_id: 1},
  {leader_name: "Dietrich Wichmann", church_id: 1},
  {leader_name: "Lydia Macintosh", church_id: 1},
  {leader_name: "Teannette van der Spuy", church_id: 1},
])
Service.create!([
  {date: "2014-08-24", leader_id: 1, service_type_id: 1, church_id: 1},
  {date: "2014-08-24", leader_id: 1, service_type_id: 2, church_id: 1},
  {date: "2014-08-31", leader_id: 2, service_type_id: 1, church_id: 1},
  {date: "2014-08-31", leader_id: 3, service_type_id: 2, church_id: 1},
  {date: "2014-09-07", leader_id: 2, service_type_id: 1, church_id: 1},
  {date: "2014-09-07", leader_id: 4, service_type_id: 2, church_id: 1},
  {date: "2014-09-14", leader_id: 3, service_type_id: 1, church_id: 1},
  {date: "2014-09-14", leader_id: 1, service_type_id: 2, church_id: 1},
  {date: "2014-09-21", leader_id: 2, service_type_id: 1, church_id: 1},
  {date: "2014-09-21", leader_id: 5, service_type_id: 2, church_id: 1},
  {date: "2014-09-28", leader_id: 1, service_type_id: 1, church_id: 1},
  {date: "2014-09-28", leader_id: 4, service_type_id: 2, church_id: 1},
  {date: "2014-10-05", leader_id: 2, service_type_id: 1, church_id: 1},
  {date: "2014-10-05", leader_id: 1, service_type_id: 2, church_id: 1},
  {date: "2014-10-12", leader_id: 5, service_type_id: 1, church_id: 1},
  {date: "2014-10-12", leader_id: 6, service_type_id: 2, church_id: 1},
  {date: "2014-10-19", leader_id: 2, service_type_id: 1, church_id: 1},
  {date: "2014-10-19", leader_id: 3, service_type_id: 2, church_id: 1},
  {date: "2014-10-26", leader_id: 1, service_type_id: 2, church_id: 1},
  {date: "2014-10-26", leader_id: 3, service_type_id: 1, church_id: 1},
  {date: "2014-11-09", leader_id: 3, service_type_id: 1, church_id: 1},
  {date: "2014-11-09", leader_id: 5, service_type_id: 2, church_id: 1},
  {date: "2014-11-02", leader_id: 2, service_type_id: 1, church_id: 1},
  {date: "2014-11-02", leader_id: 4, service_type_id: 2, church_id: 1},
  {date: "2014-08-17", leader_id: 5, service_type_id: 1, church_id: 1},
  {date: "2014-08-17", leader_id: 1, service_type_id: 2, church_id: 1},
  {date: "2014-08-10", leader_id: 2, service_type_id: 1, church_id: 1},
  {date: "2014-08-10", leader_id: 4, service_type_id: 2, church_id: 1},
  {date: "2014-08-03", leader_id: 3, service_type_id: 1, church_id: 1},
  {date: "2014-08-03", leader_id: 6, service_type_id: 2, church_id: 1},
  {date: "2014-11-16", leader_id: 1, service_type_id: 2, church_id: 1},
  {date: "2014-11-16", leader_id: 1, service_type_id: 1, church_id: 1},
  {date: "2014-11-30", leader_id: 5, service_type_id: 1, church_id: 1},
  {date: "2014-11-23", leader_id: 2, service_type_id: 1, church_id: 1},
  {date: "2014-11-23", leader_id: 3, service_type_id: 2, church_id: 1},
  {date: "2014-12-07", leader_id: 1, service_type_id: 1, church_id: 1},
  {date: "2014-12-07", leader_id: 5, service_type_id: 2, church_id: 1},
  {date: "2014-12-14", leader_id: 5, service_type_id: 1, church_id: 1},
  {date: "2014-12-14", leader_id: 6, service_type_id: 2, church_id: 1}
])
ServiceType.create!([
  {service_type: "9:00am", weight: 2, church_id: 1},
  {service_type: "6:00pm", weight: 3, church_id: 1},
])
Song.create!([
  {song_name: "In Christ Alone", license: "Copyright © 2001 Thankyou Music", writers: "Stuart Townend & Keith Getty", lyrics_url: "", sof_number: 0, sample_url: "http://www.youtube.com/watch?v=RCeSOY5tisI", ccli_number: nil},
  {song_name: "Abide With Me", license: "Public Domain", writers: "Hen­ry F. Lyte", lyrics_url: "http://cyberhymnal.org/htm/a/b/abidewme.htm", sof_number: nil, sample_url: "http://cyberhymnal.org/htm/a/b/abidewme.htm", ccli_number: nil},
  {song_name: "Speak, O Lord", license: "Copyright © 2005 Thankyou Music", writers: "Keith Getty & Stuart Townend", lyrics_url: "", sof_number: 0, sample_url: "https://www.youtube.com/watch?v=ckhjcIOfV88", ccli_number: nil},
  {song_name: "How Deep", license: "© 2006 Sovereign Grace Praise (BMI)", writers: "Stephen Altrogge", lyrics_url: "http://www.sovereigngracemusic.org/Songs/How_Deep/13", sof_number: 0, sample_url: "http://www.sovereigngracemusic.org/Songs/How_Deep/13", ccli_number: nil},
  {song_name: "Endless Praises", license: "© 2003 Sovereign Grace Praise (BMI)", writers: "Stephen Altrogge", lyrics_url: "http://www.sovereigngracemusic.org/Songs/Endless_Praises/14", sof_number: 0, sample_url: "http://www.sovereigngracemusic.org/Songs/Endless_Praises/14", ccli_number: nil},
  {song_name: "10,000 Reasons", license: "Copyright © 2011 Thankyou Music (Admin. by EMI Christian Music Publishing)", writers: "Matt Redman, Jonas Myrin", lyrics_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=1849631", sof_number: 0, sample_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=1849631", ccli_number: nil},
  {song_name: "God Immortal", license: "© 2008 Thankyou Music (Admin. by EMI Christian Music Publishing)", writers: "Lou Fellingham, Mike Busbee, Nathan Fellingham", lyrics_url: "https://www.weareworship.com/uk/songs/song-library/showsong/806", sof_number: 0, sample_url: "https://www.weareworship.com/uk/songs/song-library/showsong/806", ccli_number: nil},
  {song_name: "How Deep The Father’s Love For Us", license: "Copyright © 1995 Thankyou Music", writers: "Stuart Townend", lyrics_url: "http://www.stuarttownend.co.uk/song/how-deep-the-fathers-love-for-us/", sof_number: 0, sample_url: "http://www.stuarttownend.co.uk/song/how-deep-the-fathers-love-for-us/", ccli_number: nil},
  {song_name: "Cornerstone", license: "Copyright © 2011 Hillsong Music Publishing (Admin. by EMI Christian Music Publishing)", writers: "Reuben Morgan, Edward Mote, Jonas Myrin, Eric Liljero, William Batchelder Bradbury", lyrics_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=1908027", sof_number: 0, sample_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=1908027", ccli_number: nil},
  {song_name: "Let Your Kingdom Come", license: "© 2006 Sovereign Grace Praise (BMI)", writers: "Bob Kauflin", lyrics_url: "http://www.sovereigngracemusic.org/Songs/Let_Your_Kingdom_Come/13", sof_number: 0, sample_url: "http://www.sovereigngracemusic.org/Songs/Let_Your_Kingdom_Come/13", ccli_number: nil},
  {song_name: "Salvation Belongs to our God", license: "Copyright © 1985 Restoration Music Ltd", writers: "Adrian Howard, Pat Turner", lyrics_url: "", sof_number: 992, sample_url: "https://www.youtube.com/watch?v=RihfmBH8JbQ", ccli_number: nil},
  {song_name: "Jesus is Lord", license: "Copyright © 2003 Thankyou Music", writers: "Stuart Townend, Keith Getty", lyrics_url: "http://www.stuarttownend.co.uk/song/jesus-is-lord/", sof_number: 1387, sample_url: "http://www.stuarttownend.co.uk/song/jesus-is-lord/", ccli_number: nil},
  {song_name: "Salvation's Song", license: "Copyright © 2007 Thankyou Music", writers: "Stuart Townend & Andrew Small", lyrics_url: "http://www.stuarttownend.co.uk/song/salvations-song/", sof_number: 2434, sample_url: "http://www.stuarttownend.co.uk/song/salvations-song/", ccli_number: nil},
  {song_name: "As the Deer", license: "Copyright © 1983 Restoration Music Ltd.", writers: "Martin J. Nystrom", lyrics_url: "", sof_number: 27, sample_url: "https://www.youtube.com/watch?v=l7Blrb88KWU", ccli_number: nil},
  {song_name: "O Sacred King", license: "Copyright © 1999 Thankyou Music", writers: "Matt Redman", lyrics_url: "", sof_number: 1493, sample_url: "http://www.youtube.com/watch?v=xNSYwW3-RFg", ccli_number: nil},
  {song_name: "Love Divine", license: "Words: Public Domain, Music: Copyright © 2007 Thankyou Music (Admin. by Capitol CMG Publishing)", writers: "Charles Wesley, Chris Eaton, John Hartley", lyrics_url: "", sof_number: 2436, sample_url: "https://www.youtube.com/watch?v=JGGcqhKShQ8", ccli_number: "4928685"},
  {song_name: "Amazing Grace", license: "Public Domain", writers: "John Newton", lyrics_url: "", sof_number: 19, sample_url: "http://www.youtube.com/watch?v=CDdvReNKKuk", ccli_number: nil},
  {song_name: "Your Blood Speaks a Better Word (Nothing But The Blood)", license: "Copyright © 2004 Thankyou Music", writers: "Matt Redman", lyrics_url: "http://worshiptogether.com/songs/songdetail.aspx?iid=563797", sof_number: 2178, sample_url: "http://worshiptogether.com/songs/songdetail.aspx?iid=563797", ccli_number: nil},
  {song_name: "Light of the World", license: "Copyright © 2001 Thankyou Music", writers: "Tim Hughes", lyrics_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=572962", sof_number: 0, sample_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=572962", ccli_number: nil},
  {song_name: "We have seen your glory", license: "Public Domain", writers: "Steph & David Ebert", lyrics_url: nil, sof_number: nil, sample_url: nil, ccli_number: nil},
  {song_name: "Create in me a clean heart, O God", license: "Public Domain", writers: "Anonymous", lyrics_url: "https://www.hymnal.net/en/hymn/ns/51", sof_number: 0, sample_url: "https://www.hymnal.net/en/hymn/ns/51", ccli_number: nil},
  {song_name: "Blessing and Honour", license: "Copyright © 1992 Integrity’s Praise! Music", writers: "Gary Sadler & Jamie Harvill", lyrics_url: "", sof_number: 675, sample_url: "https://www.youtube.com/watch?v=5m04UJ6BCrI", ccli_number: nil},
  {song_name: "Hark the Herald Angels Sing", license: "Public Domain", writers: "Charles Wesley, William H. Cummings", lyrics_url: "", sof_number: 0, sample_url: "https://www.youtube.com/watch?v=lCt1s44cfMM", ccli_number: nil},
  {song_name: "O Lord, Our Lord", license: "Copyright © 1981 Meadowgreen Music", writers: "Michael W. Smith", lyrics_url: "", sof_number: 962, sample_url: "https://www.youtube.com/watch?v=6h56LamYqyE", ccli_number: nil},
  {song_name: "Father Into Your Courts I Will Enter", license: "Copyright © 2001 Parachute Music New Zealand", writers: "Andrew Ulugia & Wayne Huirua", lyrics_url: "", sof_number: 1230, sample_url: "https://www.youtube.com/watch?v=bo2bwXLwhVs", ccli_number: nil},
  {song_name: "Standing in Your Presence", license: "Copyright © 1996 Darlene Zschech/Hillsongs Australia/Kingsway’s Thankyou Music", writers: "Darlene Zschech", lyrics_url: "", sof_number: 1011, sample_url: "https://www.youtube.com/watch?v=bK3mbyQvjDw", ccli_number: nil},
  {song_name: "Beautiful Lord, Wonderful Saviour", license: "Copyright © 1997 Darlene Zschech/Hillsong Publishing/ Kingsway Music", writers: "Darlene Zschech", lyrics_url: "", sof_number: 0, sample_url: "https://www.youtube.com/watch?v=a5g5qXLG7w4", ccli_number: nil},
  {song_name: "Your Will, Not Mine", license: "Copyright © 1991 Sovereign Lifestyle Music", writers: "Dougie Brown", lyrics_url: "", sof_number: 1149, sample_url: nil, ccli_number: nil},
  {song_name: "Tell Out, My Soul", license: "Public Domain", writers: "Timothy Dudley-Smith", lyrics_url: "", sof_number: 0, sample_url: "https://www.youtube.com/watch?v=s6ji4y9Q-K0", ccli_number: nil},
  {song_name: "Be Still My Soul", license: "Public Domain", writers: "Ka­tha­ri­na A. von Schle­gel, tr. Jane L. Borth­wick", lyrics_url: "http://cyberhymnal.org/htm/b/e/bestill.htm", sof_number: 0, sample_url: "http://cyberhymnal.org/htm/b/e/bestill.htm", ccli_number: nil},
  {song_name: "My Soul Finds Rest in God Alone (Psalm 62)", license: "Copyright © 2008 Thankyou Music", writers: "Stuart Townend , Aaron Keyes", lyrics_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=956127", sof_number: 0, sample_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=956127", ccli_number: nil},
  {song_name: "Sing To The King", license: "Copyright © 2003 worshiptogether.com Songs", writers: "Billy Foote", lyrics_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=565142", sof_number: 0, sample_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=565142", ccli_number: nil},
  {song_name: "How Firm a Foundation", license: "Copyright © 2003 songsfortoday.com", writers: "Richard Simpkin", lyrics_url: "http://www.music-ministry.org/wp-content/uploads/2014/01/How-firm-a-foundation.pdf", sof_number: 0, sample_url: "http://www.music-ministry.org/wp-content/uploads/2014/01/How-firm-a-foundation.pdf", ccli_number: nil},
  {song_name: "You Alone Can Rescue (Who, oh Lord, could save themselves)", license: "Copyright © 2009 Thankyou Music", writers: "Matt Redman, Jonas Myrin", lyrics_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=1722527", sof_number: 0, sample_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=1722527", ccli_number: nil},
  {song_name: "Before the Throne of God Above", license: "Public Domain", writers: "Charitie L. Bancroft", lyrics_url: "", sof_number: 1187, sample_url: nil, ccli_number: nil},
  {song_name: "Come Thou Fount of Every Blessing", license: "Public Domain", writers: "Robert Robinson", lyrics_url: nil, sof_number: 0, sample_url: nil, ccli_number: nil},
  {song_name: "Jesus The Name High Over All", license: "Copyright © 2008 Thankyou Music", writers: "Gareth Robinson , John Hartley , Chris Eaton", lyrics_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=1011640", sof_number: 0, sample_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=1011640", ccli_number: nil},
  {song_name: "Show Us Christ", license: "Copyright © 2011 Sovereign Grace Worship", writers: "Doug Plank, Bob Kauflin", lyrics_url: "http://www.sovereigngracemusic.org/Songs/Show_Us_Christ/2", sof_number: 0, sample_url: "http://www.sovereigngracemusic.org/Songs/Show_Us_Christ/2", ccli_number: nil},
  {song_name: "For All You've Done (My Saviour, Redeemer)", license: "Copyright © 2004 Hillsong Music Publishing", writers: "Reuben Morgan", lyrics_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=1801896", sof_number: 0, sample_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=1801896", ccli_number: nil},
  {song_name: "A Father to the Fatherless", license: "Copyright © 2003 Thankyou Music", writers: "Paul Oakley", lyrics_url: "", sof_number: 1691, sample_url: nil, ccli_number: nil},
  {song_name: "Nothing in this World", license: "Copyright © 1998 Thankyou Music", writers: "Tim Hughes", lyrics_url: "", sof_number: 1465, sample_url: nil, ccli_number: nil},
  {song_name: "Hungry, I Come to You", license: "Copyright © 1999 Vineyard Songs (UK/Eire)", writers: "Kathryn Scott", lyrics_url: "", sof_number: 1293, sample_url: nil, ccli_number: nil},
  {song_name: "At The Foot of the Cross", license: "Copyright © 2003 Vertical Worship Songs", writers: "Kathryn Scott", lyrics_url: "", sof_number: 1719, sample_url: nil, ccli_number: nil},
  {song_name: "Here I Am", license: "Copyright © 2003 Curious? Music UK/Bucks Music Ltd", writers: "Martin Smith, Stuart Garrard", lyrics_url: "", sof_number: 1827, sample_url: nil, ccli_number: nil},
  {song_name: "Merciful God", license: "Copyright © 2006 Thankyou Music", writers: "Keith & Kristyn Getty, Stuart Townend", lyrics_url: "", sof_number: 1966, sample_url: nil, ccli_number: nil},
  {song_name: "There is a Redeemer", license: "Copyright © 1982 Birdwing Music", writers: "Melody Green", lyrics_url: "", sof_number: 544, sample_url: nil, ccli_number: nil},
  {song_name: "You are the Holy One", license: "Copyright © 1988 Mercy/Vineyard Publishing", writers: "Andy Park", lyrics_url: "", sof_number: 626, sample_url: nil, ccli_number: nil},
  {song_name: "Jesus, God's Righteousness Revealed", license: "Copyright © 1995 Word Music Inc./Maranatha! Music", writers: "Geoff Bullock", lyrics_url: "", sof_number: 1383, sample_url: nil, ccli_number: nil},
  {song_name: "You Laid Aside Your Majesty (I Really Want to Worship You My Lord)", license: "Copyright © 1985 Kingsway’s Thankyou Music", writers: "Noel Richards", lyrics_url: "", sof_number: 633, sample_url: nil, ccli_number: nil},
  {song_name: "I Will Offer Up My Life", license: "Copyright © 1994 Kingsway’s Thankyou Music", writers: "Matt Redman", lyrics_url: "", sof_number: 851, sample_url: nil, ccli_number: nil},
  {song_name: "No Eye Has Seen", license: "Copyright © 1990 Integrity’s Hosanna! Music/People of Destiny Int.", writers: "Mark Altrogge", lyrics_url: "", sof_number: 943, sample_url: nil, ccli_number: nil},
  {song_name: "Lord, I Come to You", license: "Copyright © 1992 Word Music", writers: "Geoff Bullock", lyrics_url: "", sof_number: 895, sample_url: nil, ccli_number: nil},
  {song_name: "Father Here I Am", license: "Copyright © 1989 Mercy/Vineyard Publishing", writers: "Danny Daniels", lyrics_url: "", sof_number: 94, sample_url: nil, ccli_number: nil},
  {song_name: "Change My Heart, O God", license: "Copyright © 1982 Mercy/Vineyard Publishing", writers: "Eddie Espinosa", lyrics_url: "", sof_number: 58, sample_url: nil, ccli_number: nil},
  {song_name: "Guide Me, O Thou Great Jehovah", license: "Public Domain", writers: "William Williams, Tr. Peter Williams", lyrics_url: "", sof_number: 148, sample_url: nil, ccli_number: nil},
  {song_name: "Lord of the Church", license: "Copyright © Timothy Dudley-Smith", writers: "Timothy Dudley-Smith", lyrics_url: "", sof_number: 1433, sample_url: nil, ccli_number: nil},
  {song_name: "Lord Reign in Me (Over all the Earth)", license: "Copyright © 1998 Vineyard Songs (UK/Eire)", writers: "Brenton Brown", lyrics_url: nil, sof_number: 0, sample_url: nil, ccli_number: nil},
  {song_name: "All My Shame (A Frame So Beautifully Formed)", license: "Copyright © 2007 Thankyou Music", writers: "Ben Dunnett, Hannah Dunnett", lyrics_url: nil, sof_number: nil, sample_url: nil, ccli_number: nil},
  {song_name: "When I Survery", license: "Public Domain", writers: "Isaac Watts", lyrics_url: "", sof_number: 596, sample_url: nil, ccli_number: nil},
  {song_name: "Be Thou My Vision", license: "Public Domain", writers: "Tr. Eleanor Hull", lyrics_url: nil, sof_number: 0, sample_url: nil, ccli_number: nil},
  {song_name: "Above All Powers", license: "Copyright © 1999 Lensongs Publishing/Integrity's Hosanna! Music/Sovereign Music UK", writers: "Lenny LeBlanc, Paul Baloche", lyrics_url: "", sof_number: 1151, sample_url: nil, ccli_number: nil},
  {song_name: "Jesus, Thank You", license: "Copyright © 2003 Integrity’s Hosanna! Music (ASCAP)/Sovereign Grace Worship (ASCAP)", writers: "Pat Sczebel", lyrics_url: "http://www.sovereigngracemusic.org/Songs/Jesus,_Thank_You/14", sof_number: 0, sample_url: "http://www.sovereigngracemusic.org/Songs/Jesus,_Thank_You/14", ccli_number: nil},
  {song_name: "With a Prayer", license: "Copyright © 2002 Thankyou Music", writers: "Stuart Townend", lyrics_url: "", sof_number: 1627, sample_url: nil, ccli_number: nil},
  {song_name: "Lord, You are the Author of my Life", license: "Copyright © 1985 Kingsway’s Thankyou Music", writers: "Judy Pruett", lyrics_url: "", sof_number: 910, sample_url: nil, ccli_number: nil},
  {song_name: "Be Still", license: "Copyright © 1986 Kingsway’s Thankyou Music", writers: "David J. Evans", lyrics_url: "", sof_number: 40, sample_url: nil, ccli_number: nil},
  {song_name: "Holy Spirit, Living Breath of God", license: "Copyright © 2005 Thankyou Music", writers: "Keith Getty, Stuart Townend", lyrics_url: "", sof_number: 1850, sample_url: nil, ccli_number: nil},
  {song_name: "Eagles' Wings (Call the Man)", license: "Copyright © 1979, 2003, OCP", writers: "Michael Joncas", lyrics_url: nil, sof_number: nil, sample_url: nil, ccli_number: nil},
  {song_name: "Wonderful, Merciful Savior", license: "Copyright © 1989 Dayspring Music, LLC", writers: "Dawn Rodgers, Eric Wyse", lyrics_url: nil, sof_number: nil, sample_url: nil, ccli_number: nil},
  {song_name: "Come People of the Risen King", license: "Copyright © 2007 Thankyou Music", writers: "Keith & Kristyn Getty, Stuart Townend", lyrics_url: "", sof_number: 224, sample_url: nil, ccli_number: nil},
  {song_name: "I Cannot Tell", license: "Public Domain", writers: "William Y. Fullerton", lyrics_url: "", sof_number: 205, sample_url: nil, ccli_number: nil},
  {song_name: "Rock of Ages", license: "Words in this version Copyright © 2001 Make Way Music", writers: "Augustus M. Toplady (1740-78) adapt. by Graham Kendrick", lyrics_url: "", sof_number: 1507, sample_url: nil, ccli_number: nil},
  {song_name: "Take My Life and Let it Be", license: "Copyright © 2005 Thankyou Music", writers: "Frances R. Havergal (1836 –1879) Adpt. & new music Paul Oakley", lyrics_url: "", sof_number: 2037, sample_url: nil, ccli_number: nil},
  {song_name: "The Whole Earth", license: "Copyright © 2005 Hillsong Publishing/kingswaysongs.com", writers: "Reuben Morgan", lyrics_url: "", sof_number: 2067, sample_url: nil, ccli_number: nil},
  {song_name: "The Precious Blood", license: "Copyright © 2005 Sovereign Grace Worship (ASCAP)", writers: "Peter Gagnon", lyrics_url: "http://sovereigngracemusic.org/Songs/The_Precious_Blood/13", sof_number: 0, sample_url: "http://sovereigngracemusic.org/Songs/The_Precious_Blood/13", ccli_number: nil},
  {song_name: "Healing To The Nations", license: "Copyright © 1982 Scripture In Song (Admin. by Maranatha! Music (Capitol CMG))", writers: "Bob Fitts", lyrics_url: nil, sof_number: nil, sample_url: nil, ccli_number: nil},
  {song_name: "Name of All Majesty", license: "Copyright © 1979 Timothy Dudley-Smith", writers: "Timothy Dudley-Smith", lyrics_url: "", sof_number: 939, sample_url: nil, ccli_number: nil},
  {song_name: "There is a Higher Throne", license: "Copyright © 2002 Thankyou Music", writers: "Kristyn Lennox & Keith Getty", lyrics_url: "", sof_number: 1541, sample_url: nil, ccli_number: nil},
  {song_name: "We'll Walk the Land", license: "Copyright © 1989 Make Way Music", writers: "Graham Kendrick", lyrics_url: "", sof_number: 583, sample_url: nil, ccli_number: nil},
  {song_name: "Jabulani Africa (Bayete iNkosi)", license: "Public Domain?", writers: "Unknown", lyrics_url: nil, sof_number: nil, sample_url: nil, ccli_number: nil},
  {song_name: "Hosanna (Praise Is Rising)", license: "Copyright © 2005, 2006 Thankyou Music", writers: "Brenton Brown, Paul Baloche", lyrics_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=559270", sof_number: 0, sample_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=559270", ccli_number: nil},
  {song_name: "By Faith", license: "Copyright © 2009 Thankyou Music", writers: "Stuart Townend, Keith & Kristyn Getty", lyrics_url: "http://www.gettymusic.com/hymns-byfaith.aspx", sof_number: 2240, sample_url: "http://www.gettymusic.com/hymns-byfaith.aspx", ccli_number: nil},
  {song_name: "O Church, Arise", license: "Copyright © 2005 Thankyou Music", writers: "Stuart Townend, Keith Getty", lyrics_url: "http://www.gettymusic.com/hymns-ochurcharise.aspx", sof_number: 1981, sample_url: "http://www.gettymusic.com/hymns-ochurcharise.aspx", ccli_number: nil},
  {song_name: "I the Lord of sea and sky", license: "Copyright © 1991 Daniel L. Schutte and New Dawn Music", writers: "Daniel L. Schutte", lyrics_url: "", sof_number: 830, sample_url: "", ccli_number: nil},
  {song_name: "It is the Cry of My Heart", license: "Copyright © 1991 Mercy/Vineyard Publishing/Adm. by CopyCare", writers: "Terry Butler", lyrics_url: "", sof_number: 832, sample_url: "", ccli_number: nil},
  {song_name: "Jesus, What a Beautiful Name", license: "Copyright © 1995 Tanya Riches/Hillsongs Australia/Kingsway’s Thankyou Music", writers: "Tanya Riches", lyrics_url: "", sof_number: 877, sample_url: "", ccli_number: nil},
  {song_name: "Thank You for Saving Me", license: "Copyright © 1993 Curious? Music UK/Adm. by Kingsway’s Thankyou Music", writers: "Martin Smith", lyrics_url: "", sof_number: 1015, sample_url: "", ccli_number: nil},
  {song_name: "Father, Let Me Dedicate", license: "Copyright © 2003 Thankyou Music/sixsteps Music/worshiptogether.com songs/kingswaysongs.com", writers: "Verses: Laurence Tuttiet (1825–1897) Adpt. Matt Redman/Chorus: Chris Tomlin, Louie Giglio & Jesse Reeves", lyrics_url: "", sof_number: 1760, sample_url: "", ccli_number: nil},
  {song_name: "Thou, Whose Almighty Word", license: "Public Domain", writers: "John Marriott", lyrics_url: "", sof_number: 557, sample_url: "", ccli_number: nil},
  {song_name: "God of Grace", license: "Copyright © 1990 Sovereign Lifestyle Music", writers: "Chris Bowater", lyrics_url: "", sof_number: 138, sample_url: "", ccli_number: nil},
  {song_name: "All My Days", license: "Copyright © 1998 Thankyou Music", writers: "Stuart Townend", lyrics_url: "", sof_number: 1158, sample_url: "", ccli_number: nil},
  {song_name: "And Can it Be", license: "Public Domain", writers: "Charles Wesley", lyrics_url: "", sof_number: 21, sample_url: "", ccli_number: nil},
  {song_name: "I Lift My Hands", license: "Copyright © 1989 Kempen Music/Kingsway’s Thankyou Music", writers: "Andre Kempen", lyrics_url: "", sof_number: 223, sample_url: "", ccli_number: nil},
  {song_name: "God Forgave My Sin", license: "Copyright © 1972 Bud John Songs/EMI Christian Music Publishing/Adm. by CopyCare", writers: "Carol Owens", lyrics_url: "", sof_number: 129, sample_url: "", ccli_number: nil},
  {song_name: "Set My Spirit Free", license: "Public Domain", writers: "Unknown", lyrics_url: "", sof_number: 494, sample_url: "", ccli_number: nil},
  {song_name: "Oh, to see the Dawn", license: "Copyright © 2005 Thankyou Music", writers: "Keith Getty & Stuart Townend", lyrics_url: "", sof_number: 1988, sample_url: "", ccli_number: nil},
  {song_name: "Draw Me Close to You", license: "Copyright © 1994 Mercy/Vineyard Publishing/Adm. by CopyCare", writers: "Kelly Carpenter", lyrics_url: "", sof_number: 1217, sample_url: "", ccli_number: nil},
  {song_name: "King of Kings, Majesty", license: "Copyright © 1996 Sovereign Lifestyle Music", writers: "Jarrod Cooper", lyrics_url: "", sof_number: 1404, sample_url: "", ccli_number: nil},
  {song_name: "Jesus is King", license: "Copyright © 1982 Word’s Spirit of Praise Music/Adm. by CopyCare", writers: "Wendy Churchill", lyrics_url: "", sof_number: 289, sample_url: "", ccli_number: nil},
  {song_name: "Come, Now Is The Time To Worship", license: "Copyright © 1998 Vineyard Songs (UK/Eire)", writers: "Brian Doerksen", lyrics_url: nil, sof_number: 1205, sample_url: "http://www.youtube.com/watch?v=NPWq8eM4lu8", ccli_number: "2430948"},
  {song_name: "Open The Eyes Of My Heart", license: "Copyright © 1997 Integrity Hosanna! Music/Sovereign Music UK", writers: "Paul Baloche", lyrics_url: "", sof_number: 1490, sample_url: "", ccli_number: nil},
  {song_name: "Across The Lands (You're The Author Of Creation)", license: "Copyright © 2002 Thankyou Music", writers: "Stuart Townend & Keith Getty", lyrics_url: "", sof_number: 1669, sample_url: "", ccli_number: nil},
  {song_name: "There is No Other Name", license: "Copyright © 1999 Integrity’s Hosanna! Music/Sovereign Music UK", writers: "Robin Mark", lyrics_url: "", sof_number: 1546, sample_url: "", ccli_number: nil},
  {song_name: "At Your Feet We Fall", license: "Copyright © 1982 Kingsway’s Thankyou Music", writers: "David Fellingham", lyrics_url: "", sof_number: 34, sample_url: "", ccli_number: nil},
  {song_name: "All Hail King Jesus", license: "Copyright © 1984 Glory Alleluia Music/Tempo Music Publications/Adm. by CopyCare", writers: "Dave Moody", lyrics_url: "", sof_number: 7, sample_url: "", ccli_number: nil},
  {song_name: "Blessed Be Your Name", license: "Copyright © 2002 Thankyou Music", writers: "Matt Redman, Beth Redman", lyrics_url: "", sof_number: 1193, sample_url: "", ccli_number: nil},
  {song_name: "O Jesus, I Have Promised", license: "Public Domain", writers: "John Ernest Bode", lyrics_url: "", sof_number: 418, sample_url: "", ccli_number: nil},
  {song_name: "All Heaven Declares", license: "Copyright © 1987 Kingsway’s Thankyou Music", writers: "Noel and Tricia Richards", lyrics_url: "", sof_number: 10, sample_url: "", ccli_number: nil},
  {song_name: "All I Once Held Dear (Knowing You)", license: "Copyright © 1993 Make Way Music", writers: "Graham Kendrick", lyrics_url: "", sof_number: 646, sample_url: "", ccli_number: nil},
  {song_name: "Jesus Is The Name We Honour", license: "Copyright © 1991 Kingsway’s Thankyou Music", writers: "Phil Lawson Johnston", lyrics_url: "", sof_number: 870, sample_url: "", ccli_number: nil},
  {song_name: "My Lord, What Love Is This", license: "Copyright © 1989 Make Way Music", writers: "Graham Kendrick", lyrics_url: "", sof_number: 398, sample_url: "", ccli_number: nil},
  {song_name: "Thy Word", license: "Copyright © 1983 Bug & Bear Music/LCS Music Group Inc./Meadowgreen Music/EMI Christian Music Publishing/Adm. by CopyCare", writers: "Amy Grant & Michael W. Smith", lyrics_url: "", sof_number: 1066, sample_url: "", ccli_number: nil},
  {song_name: "My Jesus My Saviour", license: "Copyright © 1993 Darlene Zschech/Hillsongs Australia/Kingsway’s Thankyou Music", writers: "Darlene Zschech", lyrics_url: "", sof_number: 935, sample_url: "", ccli_number: nil},
  {song_name: "Consider Christ", license: "Copyright © 1996 Bryson Smith & Philip Percival", writers: "Bryson Smith, Philip Percival", lyrics_url: "http://us.emumusic.com/consider-christ.html", sof_number: nil, sample_url: "http://us.emumusic.com/consider-christ.html", ccli_number: nil},
  {song_name: "Jesus, Lover Of My Soul", license: "Copyright © 1992 Ezzy, Grul, McPherson/Hillsongs Australia/Kingsway’s Thankyou Music", writers: "Daniel Grul, John Ezzy, Steve McPherson", lyrics_url: "", sof_number: 874, sample_url: "", ccli_number: nil},
  {song_name: "Crown Him With Many Crowns", license: "Public Domain", writers: "Matthew Bridges & Godfrey Thring", lyrics_url: "", sof_number: 77, sample_url: "", ccli_number: nil},
  {song_name: "Purify My Heart (Refiner's Fire)", license: "Copyright © 1990 Mercy/Vineyard Publishing/Adm. by CopyCare", writers: "Brian Doerksen", lyrics_url: "", sof_number: 475, sample_url: "", ccli_number: nil},
  {song_name: "There's A Sound On The Wind", license: "Copyright © 1978 Kingsway’s Thankyou Music", writers: "Graham Kendrick", lyrics_url: "", sof_number: 547, sample_url: "", ccli_number: nil},
  {song_name: "Thank You For The Cross, Lord", license: "Copyright © 2000 Darlene Zschech/Hillsong Publishing/Kingsway Music", writers: "Darlene Zschech", lyrics_url: "", sof_number: 1528, sample_url: "", ccli_number: nil},
  {song_name: "There is a Hope", license: "Copyright © 2007 Thankyou Music", writers: "Stuart Townend & Mark Edwards", lyrics_url: "", sof_number: 2558, sample_url: "", ccli_number: nil},
  {song_name: "How Great Is Our God", license: "Copyright © 2004 sixsteps Music/worshiptogether.com songs/kingswaysongs.com/Alletrop Music/CopyCare", writers: "Chris Tomlin, Jesse Reeves & Ed Cash", lyrics_url: "", sof_number: 2065, sample_url: "", ccli_number: nil},
  {song_name: "Pour Out My Heart", license: "Copyright © 1994 Mercy/Vineyard Publishing/Adm. by CopyCare", writers: "Craig Musseau", lyrics_url: "", sof_number: 759, sample_url: "", ccli_number: nil},
  {song_name: "I Will Sing Your Praises", license: "Copyright © 1984 Kingsway’s Thankyou Music", writers: "Ian Smale", lyrics_url: "", sof_number: 92, sample_url: "", ccli_number: nil},
  {song_name: "Great In Power", license: "Copyright © 1998 Russell Fragar/Hillsong Publishing/Kingsway Music", writers: "Russell Fragar", lyrics_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=1802603", sof_number: 1501, sample_url: "http://www.worshiptogether.com/songs/songdetail.aspx?iid=1802603", ccli_number: "2582339"},
  {song_name: "Lord Jesus, Here I Stand", license: "Copyright © 1990 Kingsway’s Thankyou Music", writers: "Rae Ranford", lyrics_url: "", sof_number: 358, sample_url: "", ccli_number: ""},
  {song_name: "Hosanna (I See The King Of Glory)", license: "Copyright © 2006 Hillsong Publishing/kingswaysongs.com", writers: "Brooke Ligertwood (Brooke Fraser)", lyrics_url: "", sof_number: 1900, sample_url: "", ccli_number: "4785835"},
  {song_name: "Still (Hide Me Now)", license: "Copyright © 2002 Hillsong Publishing/kingswaysongs.com", writers: "Reuben Morgan", lyrics_url: "", sof_number: 1837, sample_url: "", ccli_number: "3940963"},
  {song_name: "I Surrender", license: "Copyright © 1988 Word’s Spirit of Praise Music/Adm. by CopyCare", writers: "Sue Rinaldi, Steve Bassett", lyrics_url: "", sof_number: 1069, sample_url: "", ccli_number: "471793"},
  {song_name: "I Know Whom I Have Believed", license: "Public Domain", writers: "Daniel Webster Whittle", lyrics_url: "", sof_number: 220, sample_url: "", ccli_number: "2648060"},
  {song_name: "No Other God", license: "Copyright © 2006 Thankyou Music", writers: "Paul Oakley", lyrics_url: "", sof_number: 1962, sample_url: "", ccli_number: "4803078"},
  {song_name: "Faithful One", license: "Copyright © 1989 Mercy/Vineyard Publishing/Adm. by CopyCare", writers: "Brian Doerksen", lyrics_url: "", sof_number: 89, sample_url: "", ccli_number: "465840"},
  {song_name: "May The Mind Of Christ My Saviour", license: "Public Domain", writers: "Kate Barclay Wilkinson", lyrics_url: "", sof_number: 1448, sample_url: "", ccli_number: "2561484"},
  {song_name: "Look to the Skies", license: "Copyright © 1984 Thankyou Music", writers: "Graham Kendrick", lyrics_url: "", sof_number: 1422, sample_url: "", ccli_number: ""},
  {song_name: "Behold the Lamb", license: "Copyright © 2007 Thankyou Music", writers: "Keith &  Kristyn Getty & Stuart Townend", lyrics_url: "", sof_number: 1724, sample_url: "", ccli_number: ""},
  {song_name: "Alleluia Praise Ye The Lord", license: "Copyright © 1989 GMH Publishing", writers: "Michael Carreira, Richard C. Miller", lyrics_url: "", sof_number: nil, sample_url: "", ccli_number: "217751"},
  {song_name: "Hope Was Born This Night", license: "Copyright © 2010 Dayspring Music, LLC (BMI) All rights reserved", writers: "Ben McDonald, Dave Fry, Sidewalk Prophets", lyrics_url: "", sof_number: nil, sample_url: "", ccli_number: ""},
  {song_name: "Days of Elijah", license: "Copyright © 1997 Daybreak Music Ltd", writers: "Robin Mark", lyrics_url: "", sof_number: 1047, sample_url: "", ccli_number: "1537904"},
  {song_name: "What Can I Do", license: "Copyright © 2005 Integrity’s Hosanna! Music/Sovereign Music UK/Make Way Music ", writers: "Graham Kendrick, Paul Baloche", lyrics_url: "", sof_number: 2131, sample_url: "", ccli_number: "4554279"},
  {song_name: "All For You", license: "Copyright © 2008 Leadworship Songs/Integrity Worship Music/Make Way Music", writers: "Paul Baloche, Graham Kendrick", lyrics_url: "", sof_number: 2409, sample_url: "", ccli_number: "5490208"},
  {song_name: "Meekness And Majesty", license: "Copyright © 1986 Kingsway’s Thankyou Music", writers: "Graham Kendrick", lyrics_url: "", sof_number: 390, sample_url: "", ccli_number: "1400"},
  {song_name: "We Three Kings", license: "Public Domain", writers: "John Henry Hopkins Jr.", lyrics_url: "", sof_number: nil, sample_url: "", ccli_number: "38002"},
  {song_name: "The Heart of Worship", license: "Copyright © 1997 Kingsway’s Thankyou Music", writers: "Matt Redman", lyrics_url: "", sof_number: 1113, sample_url: "", ccli_number: "2296522"}
])
Usage.create!([
  {song_id: 30, service_id: 1},
  {song_id: 81, service_id: 1},
  {song_id: 80, service_id: 1},
  {song_id: 82, service_id: 1},
  {song_id: 74, service_id: 1},
  {song_id: 61, service_id: 2},
  {song_id: 60, service_id: 2},
  {song_id: 7, service_id: 2},
  {song_id: 74, service_id: 2},
  {song_id: 75, service_id: 3},
  {song_id: 79, service_id: 3},
  {song_id: 12, service_id: 3},
  {song_id: 76, service_id: 3},
  {song_id: 73, service_id: 3},
  {song_id: 77, service_id: 3},
  {song_id: 78, service_id: 3},
  {song_id: 69, service_id: 4},
  {song_id: 8, service_id: 4},
  {song_id: 70, service_id: 4},
  {song_id: 71, service_id: 4},
  {song_id: 72, service_id: 4},
  {song_id: 61, service_id: 5},
  {song_id: 65, service_id: 5},
  {song_id: 67, service_id: 5},
  {song_id: 62, service_id: 5},
  {song_id: 64, service_id: 5},
  {song_id: 63, service_id: 5},
  {song_id: 68, service_id: 5},
  {song_id: 60, service_id: 6},
  {song_id: 35, service_id: 6},
  {song_id: 36, service_id: 6},
  {song_id: 3, service_id: 6},
  {song_id: 54, service_id: 7},
  {song_id: 53, service_id: 7},
  {song_id: 55, service_id: 7},
  {song_id: 56, service_id: 7},
  {song_id: 52, service_id: 7},
  {song_id: 51, service_id: 7},
  {song_id: 58, service_id: 8},
  {song_id: 57, service_id: 8},
  {song_id: 13, service_id: 8},
  {song_id: 32, service_id: 8},
  {song_id: 59, service_id: 8},
  {song_id: 40, service_id: 9},
  {song_id: 43, service_id: 9},
  {song_id: 39, service_id: 9},
  {song_id: 44, service_id: 9},
  {song_id: 42, service_id: 9},
  {song_id: 45, service_id: 9},
  {song_id: 41, service_id: 9},
  {song_id: 50, service_id: 10},
  {song_id: 48, service_id: 10},
  {song_id: 19, service_id: 10},
  {song_id: 46, service_id: 10},
  {song_id: 49, service_id: 10},
  {song_id: 47, service_id: 10},
  {song_id: 4, service_id: 11},
  {song_id: 33, service_id: 11},
  {song_id: 10, service_id: 11},
  {song_id: 31, service_id: 11},
  {song_id: 32, service_id: 11},
  {song_id: 34, service_id: 11},
  {song_id: 35, service_id: 12},
  {song_id: 36, service_id: 12},
  {song_id: 37, service_id: 12},
  {song_id: 38, service_id: 12},
  {song_id: 17, service_id: 13},
  {song_id: 14, service_id: 13},
  {song_id: 12, service_id: 13},
  {song_id: 16, service_id: 13},
  {song_id: 13, service_id: 13},
  {song_id: 15, service_id: 13},
  {song_id: 11, service_id: 13},
  {song_id: 9, service_id: 14},
  {song_id: 5, service_id: 14},
  {song_id: 19, service_id: 14},
  {song_id: 20, service_id: 14},
  {song_id: 18, service_id: 14},
  {song_id: 27, service_id: 15},
  {song_id: 25, service_id: 15},
  {song_id: 24, service_id: 15},
  {song_id: 26, service_id: 15},
  {song_id: 29, service_id: 15},
  {song_id: 28, service_id: 15},
  {song_id: 6, service_id: 16},
  {song_id: 22, service_id: 16},
  {song_id: 21, service_id: 16},
  {song_id: 23, service_id: 16},
  {song_id: 1, service_id: 16},
  {song_id: 4, service_id: 17},
  {song_id: 83, service_id: 17},
  {song_id: 84, service_id: 17},
  {song_id: 85, service_id: 17},
  {song_id: 86, service_id: 17},
  {song_id: 87, service_id: 17},
  {song_id: 88, service_id: 17},
  {song_id: 89, service_id: 17},
  {song_id: 92, service_id: 18},
  {song_id: 90, service_id: 18},
  {song_id: 91, service_id: 18},
  {song_id: 93, service_id: 18},
  {song_id: 94, service_id: 18},
  {song_id: 95, service_id: 18},
  {song_id: 0, service_id: 25},
  {song_id: 80, service_id: 26},
  {song_id: 81, service_id: 26},
  {song_id: 44, service_id: 26},
  {song_id: 38, service_id: 26},
  {song_id: 96, service_id: 26},
  {song_id: 97, service_id: 27},
  {song_id: 35, service_id: 27},
  {song_id: 71, service_id: 27},
  {song_id: 98, service_id: 27},
  {song_id: 99, service_id: 28},
  {song_id: 90, service_id: 28},
  {song_id: 100, service_id: 28},
  {song_id: 41, service_id: 28},
  {song_id: 77, service_id: 28},
  {song_id: 98, service_id: 29},
  {song_id: 102, service_id: 29},
  {song_id: 35, service_id: 29},
  {song_id: 103, service_id: 29},
  {song_id: 76, service_id: 29},
  {song_id: 47, service_id: 29},
  {song_id: 69, service_id: 30},
  {song_id: 104, service_id: 30},
  {song_id: 105, service_id: 30},
  {song_id: 106, service_id: 30},
  {song_id: 6, service_id: 30},
  {song_id: 107, service_id: 30},
  {song_id: 3, service_id: 30},
  {song_id: 108, service_id: 31},
  {song_id: 97, service_id: 31},
  {song_id: 35, service_id: 31},
  {song_id: 85, service_id: 31},
  {song_id: 109, service_id: 31},
  {song_id: 72, service_id: 31},
  {song_id: 110, service_id: 32},
  {song_id: 6, service_id: 32},
  {song_id: 111, service_id: 32},
  {song_id: 103, service_id: 32},
  {song_id: 4, service_id: 32},
  {song_id: 10, service_id: 33},
  {song_id: 8, service_id: 33},
  {song_id: 112, service_id: 33},
  {song_id: 3, service_id: 33},
  {song_id: 81, service_id: 33},
  {song_id: 69, service_id: 34},
  {song_id: 5, service_id: 34},
  {song_id: 44, service_id: 34},
  {song_id: 113, service_id: 34},
  {song_id: 62, service_id: 34},
  {song_id: 114, service_id: 34},
  {song_id: 115, service_id: 34},
  {song_id: 89, service_id: 35},
  {song_id: 37, service_id: 35},
  {song_id: 46, service_id: 35},
  {song_id: 116, service_id: 35},
  {song_id: 117, service_id: 35},
  {song_id: 118, service_id: 36},
  {song_id: 1, service_id: 36},
  {song_id: 119, service_id: 36},
  {song_id: 60, service_id: 36},
  {song_id: 120, service_id: 36},
  {song_id: 108, service_id: 37},
  {song_id: 121, service_id: 37},
  {song_id: 22, service_id: 37},
  {song_id: 122, service_id: 37},
  {song_id: 19, service_id: 37},
  {song_id: 123, service_id: 37},
  {song_id: 6, service_id: 38},
  {song_id: 121, service_id: 38},
  {song_id: 1, service_id: 38},
  {song_id: 38, service_id: 38},
  {song_id: 124, service_id: 39},
  {song_id: 121, service_id: 39},
  {song_id: 38, service_id: 39},
  {song_id: 57, service_id: 39},
  {song_id: 3, service_id: 39},
  {song_id: 70, service_id: 39},
  {song_id: 33, service_id: 42},
  {song_id: 4, service_id: 42},
  {song_id: 121, service_id: 42},
  {song_id: 24, service_id: 42},
  {song_id: 106, service_id: 43},
  {song_id: 104, service_id: 43},
  {song_id: 65, service_id: 43},
  {song_id: 48, service_id: 43},
  {song_id: 29, service_id: 43},
  {song_id: 125, service_id: 43},
  {song_id: 126, service_id: 44},
  {song_id: 45, service_id: 44},
  {song_id: 77, service_id: 44},
  {song_id: 127, service_id: 44},
  {song_id: 128, service_id: 44},
  {song_id: 129, service_id: 44},
  {song_id: 5, service_id: 44},
  {song_id: 130, service_id: 45},
  {song_id: 131, service_id: 45},
  {song_id: 53, service_id: 45},
  {song_id: 65, service_id: 45},
  {song_id: 45, service_id: 45},
  {song_id: 41, service_id: 45},
  {song_id: 132, service_id: 45},
  {song_id: 32, service_id: 46},
  {song_id: 68, service_id: 46},
  {song_id: 136, service_id: 46},
  {song_id: 134, service_id: 46},
  {song_id: 133, service_id: 46},
  {song_id: 72, service_id: 46},
  {song_id: 137, service_id: 47},
  {song_id: 138, service_id: 47},
  {song_id: 139, service_id: 47},
  {song_id: 42, service_id: 47},
  {song_id: 16, service_id: 47},
  {song_id: 126, service_id: 47},
  {song_id: 137, service_id: 48},
  {song_id: 44, service_id: 48},
  {song_id: 7, service_id: 48},
  {song_id: 52, service_id: 48},
  {song_id: 140, service_id: 48},
  {song_id: 102, service_id: 48},
  {song_id: 22, service_id: 49},
  {song_id: 141, service_id: 49},
  {song_id: 113, service_id: 49},
  {song_id: 19, service_id: 49},
  {song_id: 142, service_id: 49}
])
