update_original_var = undefined

prepAjaxUpdate = ->
  update_original_var = $(this).html()
  return

doAjaxUpdate = ->
  if update_original_var == $(this).html()
    return
  dataToSend = undefined
  dataToSend =
    key: $(this).attr('name')
    value: $(this).text().trim()
  toupdate = this
  $.ajax
    type: 'PUT'
    url: '/' + $('table.masteredit').attr('id') + '/' + $(this).parent('tr').attr('id')
    data: dataToSend
    dataType: 'JSON'
    success: (data) ->
      console.log data
      if data.result
        markUpdate $(toupdate)
        $(toupdate).siblings('td').each ->
          if $(this).text() != data.object[$(this).attr('name')] and typeof data.object[$(this).attr('name')] != 'undefined'
            $(this).text data.object[$(this).attr('name')]
            markUpdate $(this)
          return
      else
        $(toupdate).text update_original_var
        console.log 'You should check rails logs because something went wrong with that update'
        trueColor = $(toupdate).css('backgroundColor')
        $(toupdate).animate { backgroundColor: '#ffe2cc' },
          duration: 100
          complete: ->
            # reset
            $(toupdate).delay(10).animate { backgroundColor: trueColor }, duration: 900
            return
      return
  return

markUpdate = (el) ->
  trueColor = $(el).css('backgroundColor')
  $(el).animate { backgroundColor: '#cce2ff' },
    duration: 100
    complete: ->
      # reset
      $(el).delay(10).animate { backgroundColor: trueColor }, duration: 900
      return
  return

$(document).on 'ready page:load', ->
  $('td[contenteditable=true]').on('focus', prepAjaxUpdate).on 'blur', doAjaxUpdate
  $('[contenteditable=true]').bind 'paste', (e) ->
    that = this
    setTimeout (->
      $(that).html $(that).text()
      return
    ), 0
    return
  return

# ---
# generated by js2coffee 2.0.1